export const tech = [
  { name: "React", image: "/react.svg.png" },
  { name: "Node", image: "/nodejsStackedLight.svg" },
  { name: "Next", image: "/next.jpg" },
  { name: "Vite", image: "/vite.png" },
  { name: "Tailwind CSS", image: "/tailwind.svg.png" },
  { name: "MySQL", image: "/MySQL.png" },
  { name: "Flask", image: "/Flask.png" },
  { name: "Express", image: "/express.jpg" },
  { name: "Supabase", image: "/supabase.png" },
  { name: "PostgreSQL", image: "/PostgresSQL.png" },
  { name: "Jupyter", image: "/Jupyter.png" },
  { name: "Docker", image: "/Docker.png" },
  { name: "NumPy", image: "/NumPy.png" },
  { name: "Pandas", image: "/Pandas.png" },
  { name: "SKlearn", image: "/scikit-learn.png" },
  { name: "Matplotlib", image: "/Matplotlib.png" },
  { name: "Linux", image: "/Linux.png" },
];
