export const tech = [
  { name: "React", image: "/react.svg.png" },
  { name: "Next.js", image: "/next.jpg" },
  { name: "Node.js", image: "/nodejsStackedLight.svg" },
  { name: "VS Code", image: "/vscode.png" },
  { name: "Vite", image: "/vite.png" },
  { name: "Tailwind CSS", image: "/tailwind.svg.png" },
  { name: "MySQL", image: "/MySQL.png" },
  { name: "Docker", image: "/Docker.png" },
  { name: "PostgreSQL", image: "/PostgresSQL.png" },
  { name: "Figma", image: "/figma.webp" },
  { name: "AWS", image: "/aws.webp" },
  { name: "FastAPI", image: "/fastapi.webp" },
  { name: "Claude", image: "/claude.webp" },
  { name: "Express.js", image: "/express.jpg" },
  { name: "Flask", image: "/Flask.png" },
  { name: "Supabase", image: "/supabase.png" },
  { name: "Jupyter", image: "/Jupyter.png" },
  { name: "NumPy", image: "/NumPy.png" },
  { name: "Pandas", image: "/Pandas.png" },
  { name: "scikit-learn", image: "/scikit-learn.png" },
  { name: "Matplotlib", image: "/Matplotlib.png" },
  { name: "Linux", image: "/Linux.png" }
];